### ISSUE TITLE
How to use `collectors.WithGoCollections(collectors.GoRuntimeMetricsCollection)`

### ISSUE THREAD

**Issue by kjgorman** [prometheus/client_golang#1082]
Hi there - I'm interested in attempting to enable the new `runtime/metrics` collector included in this package.

I can't quite see how to actually get this to work though - I was expecting to need to do something like this:

```go
package main

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
)

func main() {
	prometheus.MustRegister(collectors.NewGoCollector(
		collectors.WithGoCollections(collectors.GoRuntimeMetricsCollection),
	))
}
```

but this panics with a duplicate metric:

```
$ go run main.go
panic: descriptor Desc{fqName: "go_memory_classes_total_bytes", help: "All memory mapped by the Go runtime into the current process as read-write. Note that this does not include memory mapped by code called via cgo or via the syscall package. Sum of all metrics in /memory/classes.", constLabels: {}, variableLabels: []} already exists with the same fully-qualified name and const label values

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000163f58?, {0xc000012320?, 0x1, 0x0?})
        /Users/kierangorman/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:403 +0x7f
github.com/prometheus/client_golang/prometheus.MustRegister(...)
        /Users/kierangorman/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:178
main.main()
        /Users/kierangorman/src/github.com/kjgorman/collector-repro/main.go:9 +0xb8
exit status 2
```

it seems related to the collector registered in an `init` function, [here](https://github.com/prometheus/client_golang/blob/v1.12.2/prometheus/registry.go#L63). (i.e., by removing that collector registration, mine works in `main.main`).

This reproduces at the most recent tagged version:

```
module github.com/kjgorman/collector-repro

go 1.18

require github.com/prometheus/client_golang v1.12.2

require (
        github.com/beorn7/perks v1.0.1 // indirect
        github.com/cespare/xxhash/v2 v2.1.2 // indirect
        github.com/golang/protobuf v1.5.2 // indirect
        github.com/matttproud/golang_protobuf_extensions v1.0.1 // indirect
        github.com/prometheus/client_model v0.2.0 // indirect
        github.com/prometheus/common v0.35.0 // indirect
        github.com/prometheus/procfs v0.7.3 // indirect
        golang.org/x/sys v0.0.0-20220520151302-bc2c85ada10a // indirect
        google.golang.org/protobuf v1.28.0 // indirect
)
```

is this a bug or am I holding it wrong?

**Comment by rogerogers** [comment]
You should init a registry first
like this
```go
package main

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
)

func main() {
	reg := prometheus.NewRegistry()
	reg.MustRegister(collectors.NewGoCollector(
		collectors.WithGoCollections(collectors.GoRuntimeMetricsCollection),
	))
	reg.Gather()
}

```

**Comment by kjgorman** [comment]
I understand I could create a separate registry, but it still seems incorrect that registering to the default should be causing a duplicate metric panic when I've requested only to register new runtime/metrics metrics. i.e., I would expect this to be additive only.

**Comment by kakkoyun** [comment]
Hey @kjgorman, thanks for asking. I think @rogerogers has answered your question.

Maybe it's not clear from the message, you're trying to register already registered metrics again. As mentioned above, by default GoCollector is registered to the default registry.

You can also find an example over here https://github.com/prometheus/client_golang/blob/main/examples/gocollector/main.go
