### ISSUE TITLE
It's not possible to add GoRuntimeMetricsCollection to default registerer

### ISSUE THREAD

**Issue by jan-dubsky** [prometheus/client_golang#1124]
## Problem description

I'm using v1.13.0 that added example describing how to create a collector collecting `GoRuntimeMetricsCollection` (removed as default in v1.12.2). I try to achieve the same behaviour that has been default pre-v1.12.2. In other words, I want to add collector with `GoRuntimeMetricsCollection` to `DefaultRegisterer`. Unfortunately following attempt panics because of duplicate base metrics:
```
func init() {
	prometheus.MustRegister(
		collectors.NewGoCollector(
			collectors.WithGoCollectorRuntimeMetrics(
				collectors.MetricsGC,
				collectors.MetricsMemory,
				collectors.MetricsScheduler,
			),
			collectors.WithGoCollectorMemStatsMetricsDisabled(),
		),
	)
}
```
With following message:
```
panic: descriptor Desc{fqName: "go_info", help: "Information about the Go environment.", constLabels: {version="go1.19"}, variableLabels: []} already exists with the same fully-qualified name and const label values

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0000e9cc8?, {0xc0000647e0?, 0x1, 0x966200?})
	/home/h/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:403 +0x7f
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/home/h/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:178
...
```

The panic is caused by metrics listed in [baseGoCollector](https://github.com/prometheus/client_golang/blob/83d56b1144a0c2eb10d399e7abbae3333bebc463/prometheus/go_collector.go#L216) that are by default added to [every collector](https://github.com/prometheus/client_golang/blob/main/prometheus/go_collector_latest.go#L95). Because one collector is already registered to `DefaultRegisterer` by [init function](https://github.com/prometheus/client_golang/blob/main/prometheus/registry.go#L63) of `client_golang` package, the code above tries to register an already registered metrics and panics because of that. 

# Proposed solution
Either add an example adding `GoRuntimeMetricsCollection` to `DefaultRegisterer` (if there is any way), or add an option to disable `baseGoCollector` metrics in a newly created collector.

**Comment by jan-dubsky** [comment]
There is an Example describing this: https://github.com/prometheus/client_golang/blob/v1.13.0/prometheus/collectors/go_collector_latest_test.go#L284
