### ISSUE TITLE
const metric: inconsistent label cardinality with curried variable labels

### ISSUE THREAD

**Issue by xyluet** [prometheus/client_golang#838]
I just started research about custom exporter, sorry for bad issue title. 

```go
package main

import (
	"fmt"
	"net/http/httptest"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

type appCollector struct {
	idleDesc   *prometheus.Desc
	activeDesc *prometheus.Desc
}

func (c *appCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- c.idleDesc
	ch <- c.activeDesc
}

func (c *appCollector) Collect(ch chan<- prometheus.Metric) {
	// get from somewhere
	idle := 1.
	active := 2.

	ch <- prometheus.MustNewConstMetric(c.idleDesc, prometheus.GaugeValue, idle)
	ch <- prometheus.MustNewConstMetric(c.activeDesc, prometheus.GaugeValue, active)
}

func main() {
	appGaugeVec := promauto.NewGaugeVec(prometheus.GaugeOpts{
		Name: "app_status_count",
	}, []string{"status"})

	appCollector := &appCollector{
		idleDesc:   appGaugeVec.With(prometheus.Labels{"status": "idle"}).Desc(),
		activeDesc: appGaugeVec.With(prometheus.Labels{"status": "active"}).Desc(),
	}

	registry := prometheus.NewRegistry()
	registry.MustRegister(appCollector)

	w, r := httptest.NewRecorder(), httptest.NewRequest("", "/", nil)
	promhttp.HandlerFor(registry, promhttp.HandlerOpts{}).ServeHTTP(w, r)
	fmt.Println(w.Body)
}
```

```
panic: inconsistent label cardinality: expected 1 label values but got 0 in []string(nil)

goroutine 10 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
        /home/ali/.asdf/installs/golang/1.14.7/packages/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/value.go:107
main.(*appCollector).Collect(0xc000021a00, 0xc000078e40)
        /home/ali/Desktop/projects/pf/github/marketing-api/cmd/test/main.go:27 +0x169
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/ali/.asdf/installs/golang/1.14.7/packages/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:446 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/ali/.asdf/installs/golang/1.14.7/packages/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:457 +0x599
exit status 2
```

I can just make 2 gauge vecs, but why it didn't work?

**Comment by beorn7** [comment]
You are not generating a descriptor with constant labels. So you either have to pass the label when creating the constMetric, or you have to create a descriptor with constant labels.

For the former, do something like `ch <- prometheus.MustNewConstMetric(c.idleDesc, prometheus.GaugeValue, idle, "idle")`

For the latter, create the descriptor with `prometheus.NewDesc("app_status_count", "help", nil, prometheus.Labels{"status": "idle"})`

If you have more questions about how to use this package, please ask them on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
